server:
  port: 8001
  forward-headers-strategy: framework

spring:
  application:
    name: quoteservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authservice:9000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
