server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: authservice
  security:
    oauth2:
      authorizationserver:
        issuer: http://authservice:9000


