server:
  port: 8000

spring:
  application:
    name: jokeservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authservice:9000

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
