server:
  port: 8080

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      mvc:
        routes:
          - id: jokes_random_route
            uri: http://jokeservice:8000
            predicates:
              - Path=/jokes/random
          - id: quotes_random_route
            uri: http://quoteservice:8001
            predicates:
              - Path=/quotes/random

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
