server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: GATEWAY_SESSION


spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      mvc:
        routes:
          - id: jokes_random_route
            uri: http://localhost:8000
            predicates:
              - Path=/jokes/random
          - id: quotes_random_route
            uri: http://localhost:8001
            predicates:
              - Path=/quotes/random

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
